#!/usr/bin/env python3
"""Generate private passage-note prototypes from curated metadata."""

from __future__ import annotations

import argparse
import html
from pathlib import Path
from typing import Any

import yaml

from lib.extraction_common import (
    git_commit,
    load_config,
    now_utc,
    project_path,
    relative_to_root,
    resolve_source_paths,
    sha256_file,
    write_csv,
)
from lib.workspace_components import backlink_list, link, note_meta, passage_card, private_banner, provenance_table


SCRIPT_VERSION = "1"
DEFAULT_INPUT = "data/passage-notes.yml"
DEFAULT_OUTPUT_DIR = "docs/workspace/passages"


def load_passage_notes(path: str | Path) -> list[dict[str, Any]]:
    input_path = project_path(path)
    if not input_path.exists():
        return []
    with input_path.open("r", encoding="utf-8") as file_obj:
        payload = yaml.safe_load(file_obj) or {}
    notes = payload.get("passage_notes", [])
    if not isinstance(notes, list):
        raise ValueError(f"passage_notes must be a list in {input_path}")
    return [note for note in notes if isinstance(note, dict)]


def markdown_list(values: list[str], empty: str) -> str:
    if not values:
        return f"- {html.escape(empty)}"
    return "\n".join(f"- {value}" for value in values)


def note_text(note: dict[str, Any], key: str, default: str = "") -> str:
    return str(note.get(key, default)).strip()


def passage_url(note_id: str) -> str:
    return f"{note_id}.md"


def site_passage_link(note: dict[str, Any], prefix: str = "") -> str:
    return f"[{html.escape(str(note.get('title', note.get('id', 'Untitled Passage'))))}]({prefix}{passage_url(str(note.get('id', '')))})"


def chapter_links(note: dict[str, Any], prefix: str = "../../../") -> list[str]:
    links = []
    for raw_path in note.get("chapter_candidates", []) or []:
        path = str(raw_path)
        label = Path(path).stem.replace("-", " ").title()
        href = prefix + path.removeprefix("docs/")
        links.append(link(label, href.replace(".md", "/")))
    return links


def build_passage_note(note: dict[str, Any], source: dict[str, Any], output_path: Path) -> str:
    note_id = str(note["id"])
    text_id = str(note["text_id"])
    thinker_slug = str(note["thinker_slug"])
    constellation_ids = [str(value) for value in note.get("constellation_ids", [])]
    tags = [str(value) for value in note.get("tags", [])]
    generated_at = now_utc()

    constellation_links = [link(value, f"../../{value}/") for value in constellation_ids]
    chapters = chapter_links(note)

    title = note_text(note, "title", note_id)
    source_location = note_text(note, "source_location")
    source_edition = note_text(note, "source_edition")
    rights_mode = note_text(note, "rights_mode")
    paraphrase = note_text(note, "paraphrase")
    commentary = note_text(note, "commentary")

    return f"""# {html.escape(title)}

{note_meta([
    ("Type", "passage note"),
    ("Status", note.get("status", "prototype")),
    ("Source mode", note.get("source_mode", "restricted paraphrase only")),
    ("Tags", ", ".join(tags) or "TBD"),
])}

{private_banner("Private passage note", "This prototype is paraphrase-only. Do not add copied source prose until the edition and rights path are explicit.")}

## Passage Handle

{html.escape(title)}

## Source And Rights

| Field | Value |
| --- | --- |
| Thinker | [{html.escape(str(note.get("thinker", thinker_slug)))}](../thinkers/{thinker_slug}.md) |
| Text | [{html.escape(str(note.get("text_title", text_id)))}](../norton-texts/{text_id}.md) |
| Source location | {html.escape(source_location)} |
| Edition | {html.escape(source_edition)} |
| Rights mode | {html.escape(rights_mode)} |
| Exact quotation status | pending; no copied source prose on this page |

## Paraphrase

{html.escape(paraphrase)}

## Project Commentary

{html.escape(commentary)}

## Passage Card

{passage_card("Passage Prototype", title, [
    ("Source location", html.escape(source_location)),
    ("Rights mode", html.escape(rights_mode)),
    ("Use", html.escape(commentary)),
])}

## Backlinks

{backlink_list([
    link("Passage Notes", "../"),
    link(str(note.get("text_title", text_id)), f"../../norton-texts/{text_id}/"),
    link(str(note.get("thinker", thinker_slug)), f"../../thinkers/{thinker_slug}/"),
    *constellation_links,
    *chapters,
])}

## Provenance

{provenance_table([
    ("Source-derived metadata", "Passage title, source location, text ID, thinker, rights mode, tags, and links come from `data/passage-notes.yml`."),
    ("Generated scaffold", "This page is generated by `scripts/update_workspace_passage_notes.py`."),
    ("Human commentary", "Paraphrase and project commentary are curated prototype notes and require review before public use."),
    ("Copied source prose", "None. This page contains no copied Norton source prose."),
])}

## Review Tasks

{markdown_list([html.escape(str(value)) for value in note.get("review_tasks", []) or []], "No review tasks recorded yet.")}

## Audit Trail

| Field | Value |
| --- | --- |
| Passage ID | `{note_id}` |
| Source ID | `{source["source_id"]}` |
| Source title | {html.escape(str(source.get("source_title", "")))} |
| Source rights status | `{html.escape(str(source.get("source_rights_status", "unknown")))}` |
| Generated at | `{generated_at}` |
| Git commit | `{git_commit()}` |
| Script version | `{SCRIPT_VERSION}` |
| Output path | `{relative_to_root(output_path)}` |
"""


def build_index(notes: list[dict[str, Any]], source: dict[str, Any], output_path: Path) -> str:
    rows = []
    for note in sorted(notes, key=lambda item: str(item.get("id", ""))):
        rows.append(
            "| "
            + " | ".join(
                [
                    site_passage_link(note),
                    html.escape(str(note.get("text_title", note.get("text_id", "")))),
                    html.escape(str(note.get("thinker", note.get("thinker_slug", "")))),
                    ", ".join(html.escape(str(value)) for value in note.get("constellation_ids", []) or []),
                    html.escape(str(note.get("rights_mode", ""))),
                ]
            )
            + " |"
        )
    generated_at = now_utc()
    return f"""# Passage Notes

This private index collects small passage-level notes for the workspace. These are the high-leverage units that connect texts, thinkers, constellations, chapters, and future public commentary.

{private_banner("Private passage index", "These notes are paraphrase-first prototypes unless a page explicitly records a cleared edition and quotation status.")}

## Current Passage Notes

| Passage | Text | Thinker | Constellations | Rights Mode |
| --- | --- | --- | --- | --- |
{chr(10).join(rows) or "| No passage notes yet |  |  |  |  |"}

## Use Pattern

1. Start from a text or thinker note.
2. Open a passage note for the smallest useful unit of argument.
3. Follow its constellation and chapter backlinks.
4. Promote only after source location, edition, and rights status are reviewed.

## Provenance

{provenance_table([
    ("Source-derived metadata", "Passage records come from `data/passage-notes.yml`."),
    ("Generated scaffold", "This index is generated by `scripts/update_workspace_passage_notes.py`."),
    ("Copied source prose", "None."),
])}

## Audit Trail

| Field | Value |
| --- | --- |
| Source ID | `{source["source_id"]}` |
| Source title | {html.escape(str(source.get("source_title", "")))} |
| Passage count | {len(notes)} |
| Generated at | `{generated_at}` |
| Git commit | `{git_commit()}` |
| Script version | `{SCRIPT_VERSION}` |
| Output path | `{relative_to_root(output_path)}` |
"""


def clean_output_dir(output_dir: Path) -> None:
    if not output_dir.exists():
        return
    for path in output_dir.glob("*.md"):
        path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="data/extraction-sources.yml")
    parser.add_argument("--source-id", default="norton-theory-criticism")
    parser.add_argument("--input", default=DEFAULT_INPUT)
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--text-id", action="append", help="Only generate notes for a specific text ID. Repeat for multiple texts.")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    source = load_config(args.config, args.source_id)
    paths = resolve_source_paths(source)
    notes = load_passage_notes(args.input)
    if args.text_id:
        requested = set(args.text_id)
        notes = [note for note in notes if str(note.get("text_id", "")) in requested]

    output_dir = Path(args.output_dir)
    planned_outputs: list[tuple[Path, str, dict[str, str]]] = []
    index_path = output_dir / "index.md"
    planned_outputs.append((index_path, build_index(notes, source, index_path), {"passage_id": "index", "text_id": ""}))
    for note in sorted(notes, key=lambda item: str(item.get("id", ""))):
        output_path = output_dir / f"{note['id']}.md"
        planned_outputs.append((output_path, build_passage_note(note, source, output_path), {"passage_id": str(note["id"]), "text_id": str(note.get("text_id", ""))}))

    if args.dry_run:
        for output_path, markdown, _audit in planned_outputs:
            print(f"--- {relative_to_root(output_path)} ---")
            print(markdown)
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    if args.clean:
        clean_output_dir(output_dir)

    generated_at = now_utc()
    audit_rows = []
    for output_path, markdown, audit in planned_outputs:
        output_path.write_text(markdown, encoding="utf-8")
        audit_rows.append(
            {
                "passage_id": audit["passage_id"],
                "text_id": audit["text_id"],
                "output_file": relative_to_root(output_path),
                "output_sha256": sha256_file(output_path),
                "source_config": source.get("_config_path", args.config),
                "passage_notes": args.input,
                "status": "ok",
                "error": "",
                "generated_at": generated_at,
                "git_commit": git_commit(),
                "script_version": SCRIPT_VERSION,
            }
        )

    write_csv(
        paths["audit_dir"] / "workspace-passage-notes.csv",
        [
            "passage_id",
            "text_id",
            "output_file",
            "output_sha256",
            "source_config",
            "passage_notes",
            "status",
            "error",
            "generated_at",
            "git_commit",
            "script_version",
        ],
        audit_rows,
    )
    print(f"Wrote {len(planned_outputs)} workspace passage note files to {relative_to_root(output_dir)}")
    print(f"Wrote workspace passage note audit to {relative_to_root(paths['audit_dir'] / 'workspace-passage-notes.csv')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
